---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package, and update repository
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_pkg }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"