---

- hosts: all
  become: true
  pre_tasks:

  - name: upadte repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: upadte repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: webservers
  become: true
  roles:
    - webservers

- hosts: db_servers
  become: true
  roles:
    - db_servers  

- hosts: file_servers
  become: true
  roles:
    - file_servers 







